define([], function() { return { Modules : 
	[  
	   {  
	      name:'Gain',
	      shortName:'gain0',
	      g_params:{  
	         min:0,
	         max:2,
	         val:1,
	         stp:0.01
	      }
	   },
	   {  
	      name:'Amplifier',
	      shortName:'gain1',
	      g_params:{  
	         min:1,
	         max:6,
	         val:1,
	         stp:0.01
	      }
	   },
	   {  
	      name:'Attenuator',
	      shortName:'gain2',
	      g_params:{  
	         min:0,
	         max:1,
	         val:0.5,
	         stp:0.01
	      }
	   },
	   {  
	      name:'On / Off',
	      shortName:'gain3',
	      g_params:{  
	         min:0,
	         max:1,
	         val:0,
	         stp:1
	      }
	   },
	   {  
	      name:'Inverter (Polarizer)',
	      shortName:'gain4',
	      g_params:{  
	         min:-1,
	         max:-1,
	         val:-1,
	         stp:1
	      }
	   },
	   {  
	      name:'VCA (-ish)',
	      shortName:'gain5',
	      g_params:{  
	         min:0,
	         max:1,
	         val:1,
	         stp:0.01
	      }
	   }
	]	
};});
