define([], function() { return { Modules : 
	[  
	   {  
	      name:'LFO',
	      shortName:'lfo1',
	      f_params:{  
	         min:0,
	         max:24,
	         val:5,
	         stp:0.1
	      },
	      g_params:{  
	         min:-200,
	         max:200,
	         val:1,
	         stp:0.01
	      },
	      w_params:{  
	         indexChecked:0
	      }
	   }
	]
};});
