define([
	], function() {
		function ModuleRenderer(master, patcher) {
			this.master = master;
            this.patcher = patcher;
			this.facades = new Array();
			this.modulesToLoadCount = 0;
			this.modulesLoadedCount = 0;
		}

		ModuleRenderer.prototype.renderModules = function(rackData) {
			var moduleTopContainerElem = document.querySelector('#moduleTopContainer');
			this.cellCounter = 0;
			
			this.renderGear(rackData, moduleTopContainer);
			
			this.modulesToLoadCount = this.countTheNumberOfModulesToLoad(rackData);
			
			this.renderRack(rackData, moduleTopContainer);
		};
		
		ModuleRenderer.prototype.renderGear = function(rackData, moduleTopContainer) {
			var self = this;
			// TODO is this used yet, does this work?
			if (rackData.gear != undefined) {
				var gearCounter = 0;
				rackData.gear.forEach(function(gear) {
					var rowId = 'gearRow' + gearCounter++;
					var rowElem = self.createRowElemAndAddToContainer(moduleTopContainer, rowId);

					var gearController = new GearController();
					var definition = { handlebarsTemplateSelector : '#gearTemplate' };
					var models = [ { gearName : gear.gearName } ];
					
					gearController.render(definition, models, '#' + rowElem.id);

					var moduleContainer = rowElem.querySelector('div.moduleContainer');

					// Modules
					gear.moduleCollections.forEach(function(moduleData) {
						moduleData.modules.forEach(function(module) {
							self.renderCellAndModule(module, moduleContainer, moduleData);
						});
					});
				});
			}
		}
		
		ModuleRenderer.prototype.renderRack = function(rackData, moduleTopContainer) {
			var self = this;
			rackData.rows.forEach(function(row) {
				var rowElem = self.createRowElemAndAddToContainer(moduleTopContainer);
				row.moduleCollections.forEach(function(moduleData) {
					moduleData.modules.forEach(function(module) {
						self.renderCellAndModule(module, rowElem, moduleData, function(facades) {
							self.logIfAllModulesHaveBeenRendered(facades);
						});
					});
				});
			});
		}
		
		ModuleRenderer.prototype.logIfAllModulesHaveBeenRendered = function(facades) {
			var f = this.facades;
			facades.forEach(function(facade, index, arr) {
				f.push(facade);
			});
			this.modulesLoadedCount += facades.length;
			if (this.modulesLoadedCount === this.modulesToLoadCount) {
				console.table(f);
			}
		}
		
		ModuleRenderer.prototype.countTheNumberOfModulesToLoad = function(rackData) {
			var moduleCount = 0;
			rackData.rows.forEach(function(row) {
				row.moduleCollections.forEach(function(moduleData) {
					moduleCount += moduleData.modules.length;
				});
			});
			return moduleCount;
		}

		ModuleRenderer.prototype.renderCellAndModule = function(module, moduleContainer, moduleData, callback) {
			var cellElem = document.createElement('div');
			cellElem.id = 'moduleCell' + this.cellCounter++;
			moduleContainer.appendChild(cellElem);

			// HTML will be generated by Handlebars in controller.render
			var containerSelector = '#' + cellElem.id;

			var modules = [];

			// Create instance of the factory specified
			var factory = new moduleData.factory();

			// Create a module instance with the moduleData
			modules.push(factory.getModule(module));

			// Create instance of the controller specified
			var controller = new moduleData.controller(this.master, this.patcher);

			// render module
			controller.render(factory.getModuleDefinition(), modules, containerSelector, callback);
		};

		ModuleRenderer.prototype.createRowElemAndAddToContainer = function(moduleTopContainerElem, id) {
			var rowElem = document.createElement('div');
			rowElem.className = 'moduleRow';
			if (id)
				rowElem.id = id;
			moduleTopContainerElem.appendChild(rowElem);
			return rowElem;
		};

		return ModuleRenderer;
	}
);