define([], function() { return { Modules : 
	[  
	   {  
	      name:'Modulator in audible range',
	      shortName:'mar1',
	      f_params:{  
	         min:20,
	         max:2000,
	         val:440,
	         stp:1
	      },
	      g_params:{  
	         min:-200,
	         max:200,
	         val:1,
	         stp:0.01
	      },
	      w_params:{  
	         indexChecked:0
	      }
	   },
	   {  
	      name:'Modulator in audible range 2',
	      shortName:'mar2',
	      f_params:{  
	         min:20,
	         max:2000,
	         val:440,
	         stp:1
	      },
	      g_params:{  
	         min:-200,
	         max:200,
	         val:1,
	         stp:0.01
	      },
	      w_params:{  
	         indexChecked:0
	      }
	   },
	   {  
	      name:'Modulator in audible range 3',
	      shortName:'mar3',
	      f_params:{  
	         min:20,
	         max:2000,
	         val:440,
	         stp:1
	      },
	      g_params:{  
	         min:-200,
	         max:200,
	         val:1,
	         stp:0.01
	      },
	      w_params:{  
	         indexChecked:0
	      }
	   }
	]
};});
